## Ejercicios - Algebra

In [1]:
import numpy as np

import random

In [2]:
# Versiones
print(f"numpy=={np.__version__}")

numpy==2.2.0


### Ejercicio 1:
- Usando la librería _**random**_, genera una matriz de $4x4$ de números enteros del 1 al 100, usando bucles.
- El resultado debe ser un _**np.array()**_.

In [3]:
# Generar directamente la matriz usando comprensión de listas
matriz = np.array([[random.randint(1, 100) for _ in range(4)] for _ in range(4)])

# Imprimir la matriz y su forma
print(matriz)
print(f"Forma de la matriz: {matriz.shape}")

[[23 77 12 33]
 [46 92 30 32]
 [37 30 54 39]
 [14 98 50 77]]
Forma de la matriz: (4, 4)


### Ejercicio 2:

- Define una función que tome como parámetro de entrada 2 valores enteros ($m$, $n$).
- La función debe generar, usando la librería _**random**_, una matriz de $mxn$ de números enteros del 1 al 100, usando bucles.
- La función debe retornar la matriz, la matriz debe ser un _**np.array()**_.

In [11]:
def generar_matriz(m, n):
    
    # Genera una matriz mxn de números enteros aleatorios entre 1 y 100.
    
    return np.array([[random.randint(1, 100) for _ in range(n)] for _ in range(m)])

# Ejemplo de uso
resultado = generar_matriz(5, 5)
print(resultado)
print(f"Forma de la matriz: {resultado.shape}")


[[28  2 43 33 21]
 [78 61 22 65 91]
 [46 53  3 31 22]
 [13 92 76 47 64]
 [75 18 99 14 26]]
Forma de la matriz: (5, 5)
