## Algebra Lineal 02

- Matrices.
- Operaciones con Matrices.
- Tipos de Matrices. 

### Matrices

Una matriz es una tabla ordenada de elementos escalares ordenados en $m$ filas y $n$ columnas:

$$
\Large A = \begin{bmatrix}
     a_{00}&      a_{01}&      a_{02}&   \cdot \cdot \cdot &      a_{0(n-2)}&      a_{0(n-1)}\\
     a_{10}&      a_{11}&      a_{12}&   \cdot \cdot \cdot &      a_{1(n-2)}&      a_{1(n-1)}\\
     a_{20}&      a_{21}&      a_{22}&   \cdot \cdot \cdot &      a_{2(n-2)}&      a_{2(n-1)}\\
        \cdot \cdot \cdot &         \cdot \cdot \cdot &         \cdot \cdot \cdot &   \cdot \cdot \cdot &             \cdot \cdot \cdot &             \cdot \cdot \cdot \\
 a_{(m-2)0}&  a_{(m-2)1}&  a_{(m-2)2}&   \cdot \cdot \cdot &  a_{(m-2)(n-2)}&  a_{(m-2)(n-1)}\\
 a_{(m-1)0}&  a_{(m-1)1}&  a_{(m-1)2}&   \cdot \cdot \cdot &  a_{(m-1)(n-2)}&  a_{(m-1)(n-1)}
\end{bmatrix}
$$

**Las matrices se denotan usualmente por letras mayúsculas, A, B, ..., y los elementos de las mismas por minúsculas, a, b, ...**

In [2]:
import numpy as np

import matplotlib
import matplotlib.pyplot as plt

In [3]:
# Versiones

print(f"numpy=={np.__version__}")
print(f"matplotlib=={matplotlib.__version__}")

numpy==2.1.3
matplotlib==3.9.4


In [5]:
# Para generar una matriz podemos crear una lista de listas y transformarlo a np.array()
# NumPy reconocerá que tiene dos dimensiones, filas y columnas

A = np.array([[  1,   2,   3,   4], 
              [ 10,  20,  30,  40], 
              [100, 200, 300, 400]])
A

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [6]:
# Podemos ver las dimensiones de una matriz usando el atributo .shape
# (filas, columnas)

A.shape

(3, 4)

### Operaciones con Matrices

#### Suma de Matrices

La suma de matrices se define como la operación que se realiza entre dos matrices que tienen las mismas dimensiones (mismo número de filas y columnas). 

El resultado de esta operación es otra matriz con las mismas dimensiones.

Los elementos de la matriz resultante se obtienen sumando los elementos correspondientes de cada posicion de las dos matrices.

Si tenemos las matrices $A_{nxm}$ y $B_{nxm}$, esta operación se denota como: $A_{nxm} + B_{nxm} = C_{nxm}$, donde $C_{nxm}$ es la matriz resultado de la operación.

$$
\Large {\begin{bmatrix}
a_{00} & a_{01}\\
a_{10} & a_{11}
\end{bmatrix} + \begin{bmatrix}
b_{00} & b_{01} \\
b_{10} & b_{11}
\end{bmatrix} = \begin{bmatrix}
a_{00} + b_{00} & a_{01} + b_{01} \\
a_{10} + b_{01} & a_{11} + b_{11}
\end{bmatrix}}
$$


Ejemplo:
$$
\Large {\begin{bmatrix}
7 & 8\\
3 & 2
\end{bmatrix} + \begin{bmatrix}
4 & -3 \\
0 & 1
\end{bmatrix} = \begin{bmatrix}
11 & 5 \\
3 & 3
\end{bmatrix}}
$$

In [7]:
# Creamos las matrices A y B
# Ambas deben de ser del mismo tamaño (igual número de filas y de columnas)

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = A + B

print("Matriz A:")
print(A)
print("Matriz B:")
print(B)
print("Resultado de A + B:")
print(C)

Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Resultado de A + B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


#### Producto escalar de Matrices

Sea la matriz $A_{nxm}$ y eselescalar $k$, el producto escalar de matrices se define como multiplicar el valor $k$ por cada elemento $a_{ij}$ de la matriz $A_{nxm}$.

$$
\Large{A = \begin{bmatrix}
a_{00} & a_{01}\\
a_{10} & a_{11}
\end{bmatrix} \longrightarrow 
k*A = \begin{bmatrix}
k \cdot a_{00} & k \cdot a_{01}\\
k \cdot a_{10} & k \cdot a_{11}
\end{bmatrix}}
$$

$$
\Large{A = \begin{bmatrix}
4 & 7\\
-1 & 0
\end{bmatrix} \longrightarrow 
7*A = \begin{bmatrix}
7 \cdot 4 & 7 \cdot 7\\
7 \cdot -1 & 7 \cdot 0
\end{bmatrix} = \begin{bmatrix}
28 & 49\\
-7 & 0
\end{bmatrix}}
$$

In [6]:
# Producto escalar de Matrices

A = np.array([[1,  2], [3, 4]])

print(f"A:")
print(A)

print(f"3*A:")
print( 3 * A )

A:
[[1 2]
 [3 4]]
3*A:
[[ 3  6]
 [ 9 12]]


#### Multiplicación de Matrices

Sean las matrices $A_{nxm}$ y $B_{mxp}$, la multiplicación de estas matrices es una matriz $C_{nxp}$, cuyos elementos se calculan de la siguiente manera: 
$$\large c_{ij} = \sum_{k = 1}^{n} a_{ik}\cdot b_{jk}$$

Si tenemos las matrices $A_{nxm}$ y $B_{mxp}$, esta operación se denota como: $A_{nxm} x B_{mxp} = C_{nxp}$, donde $C_{nxp}$ es la matriz resultado de la operación.

- **Para multiplicar matrices el número de columnas de la primera matriz debe de ser igual al número de filas de la segunda matriz.**
- **El resultado es una matriz con el número de filas de la primera matriz y el número de columnas de la segunda matriz.**

$$
\large
\begin{bmatrix}
     a_{00}&a_{01}\\
     a_{10}&a_{11}\\
     a_{20}&a_{21}
\end{bmatrix} x \begin{bmatrix}
     b_{00}&b_{01}&b_{02}\\
     b_{10}&b_{11}&b_{12}\\
\end{bmatrix} = \begin{bmatrix}
c_{00} = \sum_{k = 1}^{n} a_{0k}\cdot b_{0k} & c_{01} = \sum_{k = 1}^{n} a_{0k}\cdot b_{1k} & c_{02} = \sum_{k = 1}^{n} a_{0k}\cdot b_{2k} \\
c_{10} = \sum_{k = 1}^{n} a_{1k}\cdot b_{0k} & c_{11} = \sum_{k = 1}^{n} a_{1k}\cdot b_{1k} & c_{12} = \sum_{k = 1}^{n} a_{1k}\cdot b_{2k} \\
c_{20} = \sum_{k = 1}^{n} a_{2k}\cdot b_{0k} & c_{21} = \sum_{k = 1}^{n} a_{2k}\cdot b_{1k} & c_{22} = \sum_{k = 1}^{n} a_{2k}\cdot b_{2k} 
\end{bmatrix}
$$

Ejemplo:

$$
\Large {\begin{bmatrix}
1 & 2 \\
4 & 5 \\
7 & 8
\end{bmatrix}_{3x2} \cdot  \begin{bmatrix}
1 & 2 & 3 \\
0 & 5 & 2
\end{bmatrix}_{2x3} = \begin{bmatrix}
1 & 12 & 7 \\
4 & 33 & 22 \\
7 & 54 & 37
\end{bmatrix}_{3x3}}
$$

Para multiplicar matrices usaremos la función **np.dot()**.

In [8]:
# Creamos la matriz A
A = np.array([[1, 2],
              [4, 5],
              [7, 8]])
A

array([[1, 2],
       [4, 5],
       [7, 8]])

In [9]:
# Creamos la matriz B
B = np.array([[1, 2, 3],
              [0, 5, 2]])
B

array([[1, 2, 3],
       [0, 5, 2]])

In [10]:
# Para multiplicar matrices con NumPy usamos np\cdot dot()

C = np.dot(A, B)
C

array([[ 1, 12,  7],
       [ 4, 33, 22],
       [ 7, 54, 37]])

### Transpuesta

La traspuesta de una matriz es una operación matemática que cambia las filas por las columnas de la matriz original.

Sea la matriz $A_{nxm}$. La transpuesta de la matriz $A_{nxm}$ da como resultado una matriz $A_{mxn}$.


$$
A = \begin{bmatrix}
a_{00} & a_{01}\\
a_{10} & a_{11}\\
a_{20} & a_{21}
\end{bmatrix} \longrightarrow
A^{T} = \begin{bmatrix}
a_{00} & a_{10} & a_{20}\\
a_{01} & a_{11} & a_{21}\\
\end{bmatrix}
$$

$$
A = \begin{bmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{bmatrix} \longrightarrow
A^{T} = \begin{bmatrix}
1 & 4 & 7\\
2 & 5 & 8\\
\end{bmatrix}
$$

Para transponer una matriz usaremos el atributo **.T** de los objetos **np.array()**.

In [11]:
A = np.array([[1, 2],
              [4, 5],
              [7, 8]])
A

array([[1, 2],
       [4, 5],
       [7, 8]])

In [13]:
A.shape

(3, 2)

In [12]:
A.T # no modifica la matriz original, solo devuelve la T

array([[1, 4, 7],
       [2, 5, 8]])

In [14]:
A

array([[1, 2],
       [4, 5],
       [7, 8]])

### Tipos de matrices

#### Matriz cuadrada

Una matriz cuadrada es la que tiene el mismo número de filas que de columnas.

In [12]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Matriz identidad 

Es una matriz cuadrada con $1$ en la diagonal principal y ceros en las demás posiciones. Se suele denotar por $I$. 

Para cualquier matriz $A$, $A \cdot  I = I \cdot  A = A$

In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Matriz triangular superior

Una matriz cuadrada es triangular superior o simplemente una matriz triangular, si todas las entradas bajo la diagonal principal son iguales a cero.

In [15]:
np.triu([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [16]:
# Producto de matrices triangulares superiores

np.dot(np.triu([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), np.triu([[1, 2, 3], [4, 5, 6],[7, 8, 9]]))

array([[ 1, 12, 42],
       [ 0, 25, 84],
       [ 0,  0, 81]])

#### Matriz triangular inferior

Una matriz cuadrada es triangular inferior, si todas las entradas sobre la diagonal principal son iguales a cero.

In [17]:
np.tril([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [29]:
# Producto de matrices triangulares inferiores
np.dot(np.tril([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), np.tril([[1, 2, 3], [4, 5, 6],[7, 8, 9]]))

array([[  1,   0,   0],
       [ 24,  25,   0],
       [102, 112,  81]])

#### Matrices ortogonales 

Se dice que una matriz real A es ortogonal si cumple la siguiente ecuación: $AA^T = A^TA = I$ 

In [20]:
A = np.array([[0, 1],
              [1, 0]])
A

array([[0, 1],
       [1, 0]])

In [21]:
A.T

array([[0, 1],
       [1, 0]])

In [22]:
np.dot(A, A.T)

array([[1, 0],
       [0, 1]])

In [23]:
np.dot(A.T, A) # Es ortogonal 

array([[1, 0],
       [0, 1]])

In [24]:
B = np.array([[6, -3],
              [3,  6]])
B

array([[ 6, -3],
       [ 3,  6]])

In [25]:
B.T

array([[ 6,  3],
       [-3,  6]])

In [26]:
np.dot(B, B.T)

array([[45,  0],
       [ 0, 45]])

In [27]:
np.dot(B.T, B) # No es ortogonal

array([[45,  0],
       [ 0, 45]])

In [28]:
################################################################################################################################